Repository Marc3842h/Titan, pull requests merged in 2018-02, with the labels that each got.

#81 Fix accounts.json example commenting in README.md
  README.md
Labels: general: input wanted, status: waiting, type: documentation

#86 Hello result information!
  Titan/Managers/ThreadManager.cs
Labels: status: needs changes, type: patch

#87 Hotfix for Pull request #86
  Titan/Managers/ThreadManager.cs
Labels: status: do not merge, type: patch
